### PR TITLE
fix: raise the backtrace in test so its easier to capture

### LINKED ISSUE #307: Print exceptions when in development or test environments
During tests, if a request unexpectedly fails with a 500, there's no way to tell what went wrong. We need this code in `app/controllers/concerns/rhino/error_handling.rb#handle_uncaught_error`:

```ruby
if Rails.env.development? || Rails.env.test?
  puts exception.backtrace.join("\n")
  puts exception.message
end
```

### PR DESCRIPTION
**Pull request by jprosevear**
fixed #307

### CODE REVIEW

File: gems/rhino_project_core/app/controllers/concerns/rhino/error_handling.rb [hunk 1]
```diff
@@ -23,14 +23,16 @@ module ErrorHandling
 
       rescue_from ActiveRecord::RecordNotFound, with: :not_found
 
-      def handle_uncaught_error(exception)
+      def handle_uncaught_error(e)
+        raise e if Rails.env.test?
```
Comment (jprosevear) [inline gems/rhino_project_core/app/controllers/concerns/rhino/error_handling.rb:27]: @silaspedrosa this seemed cleaner as all the back trace filtering still applies afaict
